apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-deployment
  namespace: jenkins-ns
  labels:
    app: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      serviceAccountName: jenkins-sa
      containers:
        - name: jenkins-con
          image: mustafa2498/jenkins:latest
          ports:
            - name: httpport
              containerPort: 8080
          volumeMounts:

            - name: docker-socket
              mountPath: /var/run/
      volumes:

        - name: docker-socket
          hostPath:
            path: /var/run/