apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-deployment
  namespace: app-ns
  labels:
    app: nodejs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
       - name: nodejs-app
         image: mustafa2498/nodejs-img:v1
         ports:
         - containerPort: 3000