apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: app-ns
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  selector:
    app: nodejs
  ports:
  - name: tcp-port
    protocol: TCP
    port: 3000
    targetPort: 3000